### PR TITLE
fix pointer to time.Time

### PR DESCRIPTION
**Pull request by micanzhang**

### CODE REVIEW

**Comment by gmlewis** [comment]
Thanks, @micanzhang, but why is this change being suggested?
Does this solve a bug or issue?

**Comment by shurcooL** [comment]
The added test case fails before the change, and succeeds after. So this PR adds support for `*time.Time`. Previously, those values would be dropped during encoding. Only `time.Time` values would get encoded.

I don't know if we should or should not be supporting `*time.Time`, but if we are, then this change LGTM.

However, I'll raise a question. If we support pointer to `time.Time`, why not also support pointer to slice or array? If so, this patch (or another like it) should move the "pointer dereference" block:

```Go
for sv.Kind() == reflect.Ptr {
	if sv.IsNil() {
		break
	}
	sv = sv.Elem()
}
```

One more block higher, above `if sv.Kind() == reflect.Slice || sv.Kind() == reflect.Array {` block.

I tried out the following test case which fails now, but could be made to work by the mentioned change:

```diff
// pointers
struct {
	A *string
	B *int
	C **string
	D *time.Time
+	E *[]string `url:",space"`
}{
	A: strPtr,
	C: &strPtr,
	D: &timeVal,
+	E: &[]string{"a", "b"},
},
url.Values{
	"A": {str},
	"B": {""},
	"C": {str},
	"D": {"2000-01-01T12:34:56Z"},
+	"E": {"a b"},
},
```

**Comment by micanzhang** [comment]
@gmlewis, we use this package for http api client to encode params to query string, reference type for optional parameter. most time, we can use init value(zero value) but sometime we want to distinguish zero value and unset value, that why i suggest this change.

**Comment by micanzhang** [comment]
@shurcooL i think pointer to array and slice have the same effect after Encode for query string encoding scenario.

**Comment by shurcooL** [comment]
> i think pointer to array and slice have the same effect after Encode for query string encoding scenario.

Sorry, I'm not able to parse that. They have the same effect after what?

**Comment by micanzhang** [comment]
@shurcooL, there are some different behaviors which i not mentioned,

```
type Param struct {
              Username string 
              Location []string
              Emails *[]string 
}

var v = Param{Username:"allen"}
```

after encoding, we prefer to query string would be like `Username=allen&Location=`, `Email` should be omitted, another
way to got same result is:

```
  type Param struct {
                Username string 
                Location []string
                Emails []string `url:"Emails,omitempty"`
  }
```

**Comment by shurcooL** [comment]
I see, so you don't want pointers to slices/arrays to be included. Then nothing extra needs to be done.

**Comment by micanzhang** [comment]
yeah, pointer to a slice will be dropped if value is nil; this pull request focus on to fix pointer to time.Time; maybe we could support pointer to slice and array someday

**Comment by micanzhang** [comment]
@gmlewis, does it possible to merge this pull request?

**Comment by gmlewis** [comment]
Thank you, @micanzhang and @shurcooL.
I agree that we do not want pointers to slices or arrays.
LGTM.
Merging.

**Pull request merged**
